version: '3.5'
services:

 mariadb:
   image: mariadb:10
   hostname: mariadb
   environment:
    MYSQL_ROOT_PASSWORD: admin
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: news_analytics
   ports:
   - 3306:3306
   networks:
     - bigdata-cluster-network
 zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - bigdata-cluster-network
 kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  #127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bigdata-cluster-network
networks:
  bigdata-cluster-network:
    name : bigdata-cluster-network